### ISSUE TITLE
Consistency calculation

### ISSUE THREAD

**Issue by alonando** [entertrained/entertrained-issues#10]
This might not be a bug but I'm interested in knowing how consistency is calculated? 

I'm seeing low averages. And some times the consistency drops to 0% for two paragraphs in a row even with high WPM and accuracy scores for those same paragraphs. Here is a screenshot of my last 50 paragraphs.

![image](https://github.com/user-attachments/assets/b2f4fcc7-dabc-4ca2-b53a-9c49b968a1e3)

Again great software!, I enjoy using it.

**Comment by caderek** [comment]
Thank you for bringing this to my attention!

So there is no standard formula for how to calculate consistency, and mine was loosely based on how [Monkeytype](https://monkeytype.com/) does this (I don't know if you use it, but it's the most popular typing site currently).

So the way I measured it was to calculate the wpm for each word, and then calculate the variation coefficient using mean and standard deviation. The downside of this approach is that if your speed varies significantly, even for a small portion of the paragraph, then the standard deviation can be very big, so the very quick burst, like typing `I ` can skew the result.

Monkeytype does this similarly, but instead of calculating wpm per each word, it calculates wpm in each second of typing, which somewhat helps to smooth things out, but is still arbitrary and has a similar flaw in some cases (for example if the test time is not in full seconds, the remaining fragment skews the results as was the case in my implementation).

I could do things like Monketype, but while it would be nice to have the same method on each site, after some research I think there is a better method to do it.

---

I changed the algorithm to use a more robust method with median and [median absolute deviation](https://en.wikipedia.org/wiki/Median_absolute_deviation). This has several benefits:

* I can calculate it based on each keystroke, so there is no "resolution" limit (for example on Monkeytype if you type a very short phrase under 1s, you will get 100% consistency, no matter how inconsistent your keystrokes were),
* there are no weird edge cases with short words or fragments of seconds,
* outliers like short words, or error corrections do not skew the results in an extreme way.

Overall I think it's a better method, that shows a more useful chart, that is based on your true rhythm, not the momentary bursts and dips (they still affect consistency, just not that much).

Unfortunately, I can't change the historical data, as I do not save times per each keystroke, but all the new stats should be improved. **The update is already live in version `1.11.8`** (you can see the version in the footer of the page, you may need to refresh the page).j

Let me know if it works for you.

**Comment by alonando** [comment]
Thanks a lot for the quick response. I do notice the new calculation working and it does seem reaching +80% is attainable. With the update it adjusted to mid 50% for my last chapter. 

Since you are measuring keystroke cadence now, I wonder if you treat typos the same way or any different? I would think spamming the backspace key could skew the results but maybe that's ok as long as it is consistent.   

Thanks again

**Comment by caderek** [comment]
To be precise, what I register is the time that each character was typed, that does not include Backspace, but obviously backspacing indirectly affects that timestamps. There is no difference for this metric between long pause and you backspacing to fix a typo - so fast spamming of the Backspace does not cause the spike in the typing tempo, quite the opposite - if you backspace quickly, the pause in typing is shorter. But as I said, infrequent pauses, as well as occasional, short burst do not affect the consistency very much now.

Now, when it comes to your new result, you being at 50% mean that you have a lot of short bursts in speed, or a lot of pauses (or both). To be clear, the consistency is not the most important metric at your level, and I would not worry much about it, because typing some words faster than others is only natural before you build a solid muscle memory for less frequent words. But yeah, 80% is now definitely attainable (I type at the similar speed, and have the new consistency metric at around 70% as showed i the screenshot). It might be beneficial for your typing to try even-out your tempo deliberately, but even without deliberate effort, it should come naturally eventually.

If you consider the issue fixed, please close it or let me know that I can close it.

My recent stats:

![stats](https://i.ibb.co/6Y3pF13/entertrained-app-stats-1.png)

**Comment by alonando** [comment]
The adjustment seems to be working. Closing the issue. Thanks!
